# Generated by Django 6.0 on 2025-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', help_text='First Name', max_length=20)),
                ('last_name', models.CharField(help_text='Last Name', max_length=20)),
                ('profession', models.TextField(help_text='Profession')),
            ],
            options={
                'verbose_name': 'Main Hero Section',
                'verbose_name_plural': 'Main Hero Section',
            },
        ),
    ]
