# Generated by Django 6.0 on 2025-12-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profession',
            field=models.TextField(blank=True, help_text='Profession'),
        ),
    ]
