# Generated by Django 6.0 on 2025-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_herosection_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='profession',
        ),
        migrations.AddField(
            model_name='herosection',
            name='profession_1',
            field=models.CharField(blank=True, help_text='Profession', max_length=30),
        ),
        migrations.AddField(
            model_name='herosection',
            name='profession_2',
            field=models.CharField(blank=True, help_text='Profession', max_length=30),
        ),
    ]
