# Generated by Django 6.0 on 2025-12-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_herosection_profession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_i_am', models.TextField(blank=True, default='', help_text='Who I Am')),
                ('what_i_do', models.TextField(blank=True, default='', help_text='What I Do')),
                ('about_picture', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profession_1',
            field=models.CharField(blank=True, help_text='Profession_1', max_length=30),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profession_2',
            field=models.CharField(blank=True, help_text='Profession_2', max_length=30),
        ),
    ]
