# Generated by Django 6.0 on 2025-12-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutsection_alter_herosection_profession_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='learn_more',
            field=models.TextField(blank=True, default='', help_text='learn more link button name', max_length=40),
        ),
    ]
