# Generated by Django 6.0 on 2025-12-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutsection_learn_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='learn_more',
            field=models.CharField(blank=True, default='', help_text='learn more link button name', max_length=40),
        ),
    ]
