# Generated by Django 6.0 on 2025-12-24 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutsection_learn_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='cv',
            field=models.FileField(blank=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
