# Generated by Django 6.0 on 2025-12-24 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutsection_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='cv',
            field=models.FileField(blank=True, help_text='PDF Format', upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
