# Generated by Django 6.0 on 2025-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_aboutsection_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(blank=True, upload_to='Service Image')),
                ('service_title', models.CharField(blank=True, default='', help_text='Service Title', max_length=40)),
                ('service_info', models.TextField(blank=True, default='', help_text='Service Information')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Section',
            },
        ),
    ]
