# Generated by Django 6.0 on 2025-12-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_servicessection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='service_img',
            field=models.ImageField(upload_to='Service Image'),
        ),
    ]
