# Generated by Django 6.0 on 2025-12-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_aboutsection_about_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(help_text='Site Logo', upload_to='images/')),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logo',
            },
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='about_picture',
            field=models.ImageField(help_text='About Section Image', upload_to='images/'),
        ),
    ]
