# Generated by Django 6.0 on 2025-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitelogo_alter_aboutsection_about_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='', help_text='Blog Author Name', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_title', models.TextField(default='', help_text='Blog Title')),
                ('blog_img', models.ImageField(help_text='Blog Image', upload_to='Blog Image')),
                ('blog_para_1', models.TextField(default='', help_text='Blog Paragraph 1')),
                ('blog_para_2', models.TextField(default='', help_text='Blog Paragraph 2')),
                ('blog_para_3', models.TextField(default='', help_text='Blog Paragraph 3')),
                ('blog_para_4', models.TextField(default='', help_text='Blog Paragraph 4')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Section',
            },
        ),
    ]
