# Generated by Django 6.0 on 2025-12-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blogssection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogssection',
            options={'verbose_name': 'Blogs Section', 'verbose_name_plural': 'Blogs Section'},
        ),
    ]
