# Generated by Django 6.0 on 2025-12-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_blogssection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicessection',
            options={'verbose_name': 'Services Section', 'verbose_name_plural': 'Services Section'},
        ),
    ]
