# Generated by Django 6.0 on 2025-12-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_servicessection_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogssection',
            name='blog_para_1',
        ),
        migrations.RemoveField(
            model_name='blogssection',
            name='blog_para_2',
        ),
        migrations.RemoveField(
            model_name='blogssection',
            name='blog_para_3',
        ),
        migrations.RemoveField(
            model_name='blogssection',
            name='blog_para_4',
        ),
        migrations.CreateModel(
            name='BlogParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Blog Paragraph')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='main.blogssection')),
            ],
            options={
                'verbose_name': 'Blog Paragraph',
                'verbose_name_plural': 'Blog Paragraphs',
            },
        ),
    ]
