# Generated by Django 6.0 on 2025-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_blogssection_blog_para_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, help_text='Skill Name', max_length=60)),
                ('skill_percent', models.PositiveIntegerField(help_text='Skill Percent (0–100)')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
