# Generated by Django 6.0 on 2025-12-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_skillssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, help_text='Language Name', max_length=60)),
                ('language_percent', models.PositiveIntegerField(help_text='Language Percent (0–100)')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
