# Generated by Django 6.0 on 2025-12-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_locationsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationsection',
            options={'verbose_name': 'Your location', 'verbose_name_plural': 'Your location'},
        ),
    ]
