# Generated by Django 6.0 on 2025-12-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_locationsection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Required. A valid email address.', max_length=254, unique=True)),
                ('location_description_1', models.CharField(help_text='Add Street, Society', max_length=350)),
                ('location_description_2', models.CharField(help_text='Add City, Country', max_length=350)),
                ('map_location', models.TextField(help_text='Add Google Maps Geolocation')),
            ],
            options={
                'verbose_name': 'ContactInfo',
                'verbose_name_plural': 'ContactInfo',
            },
        ),
        migrations.DeleteModel(
            name='LocationSection',
        ),
    ]
