# Generated by Django 6.0 on 2025-12-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contactinfo_delete_locationsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
    ]
