# Generated by Django 6.0 on 2025-12-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_contactinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contact_availability',
            field=models.TextField(help_text='Your Contact Availability Information', null=True),
        ),
    ]
