# Generated by Django 6.0 on 2025-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contactinfo_contact_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_year', models.PositiveIntegerField(help_text='Starting Year')),
                ('ending_year', models.PositiveIntegerField(help_text='Ending Year')),
                ('institute_university_name', models.CharField(help_text='Institute University Name', max_length=300)),
                ('degree_role', models.CharField(help_text='What You Did', max_length=300)),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timeline',
            },
        ),
    ]
