# Generated by Django 6.0 on 2025-12-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the experience or achievement', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Describe what you did')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timeline', models.ForeignKey(help_text='Select the timeline this experience belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='main.timeline')),
            ],
            options={
                'verbose_name': 'Timeline Experience',
                'verbose_name_plural': 'Timeline Experiences',
            },
        ),
    ]
