# Generated by Django 6.0 on 2025-12-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_timelineexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='ending_year',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='starting_year',
            new_name='start_year',
        ),
        migrations.RemoveField(
            model_name='timelineexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='timelineexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='timelineexperience',
            name='end_year',
            field=models.PositiveIntegerField(help_text='Ending Year', null=True),
        ),
        migrations.AddField(
            model_name='timelineexperience',
            name='start_year',
            field=models.PositiveIntegerField(help_text='Starting Year', null=True),
        ),
    ]
