# Generated by Django 6.0 on 2025-12-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_ending_year_timeline_end_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Presentation Title', max_length=350)),
                ('presentation_image', models.ImageField(help_text='Upload Presentation Image', upload_to='images/')),
                ('presentation_link', models.TextField(help_text='Enter Presentation Link')),
            ],
            options={
                'verbose_name': 'Presentation Section',
                'verbose_name_plural': 'Presentation Section',
            },
        ),
        migrations.AlterField(
            model_name='timelineexperience',
            name='title',
            field=models.CharField(help_text='Title of the experience or achievement', max_length=350),
        ),
    ]
