# Generated by Django 6.0 on 2026-01-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_presentationsection_alter_timelineexperience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_link',
            field=models.TextField(help_text='Add Instagram', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_link',
            field=models.TextField(help_text='Add Linkedin Link', null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='youtube_link',
            field=models.TextField(help_text='Add Youtube Link', null=True),
        ),
    ]
