# Generated by Django 6.0 on 2026-01-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_contactinfo_instagram_link_contactinfo_linkedin_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkillsCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter Presentation Title', max_length=350)),
                ('value', models.PositiveIntegerField(help_text='Enter Project/Experience Value')),
            ],
            options={
                'verbose_name': 'Project Skills Counter Section',
                'verbose_name_plural': 'Project Skills Counter Section',
            },
        ),
    ]
