# Generated by Django 6.0 on 2026-01-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_projectskillscounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='fav_icon_16_png',
            field=models.ImageField(help_text='fav icon 16x16 png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='fav_icon_32_png',
            field=models.ImageField(help_text='fav icon 32x32 png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sitelogo',
            name='fav_icon_ico',
            field=models.ImageField(help_text='fav icon ico', null=True, upload_to='images/'),
        ),
    ]
