# Generated by Django 6.0 on 2026-01-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_sitelogo_fav_icon_16_png_sitelogo_fav_icon_32_png_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelogo',
            name='footer_logo',
            field=models.ImageField(help_text='Footer Logo', null=True, upload_to='images/'),
        ),
    ]
